import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'
import Logo from '../assets/Logo.svg'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Catálogo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <header>
        <Image src={Logo} width={160} height={53} alt='Logo'></Image>
      </header>
      <main>{children}</main>
      <footer>© Todos os Diretos Reservados - Gustavo e Lívia</footer>
    </>
  )
}
